[project]
name = "aws-convert-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.10",
    "pydantic>=2.11.4",
    "pytest>=8.3.5",
    "ruff>=0.11.8",
    "streamlit>=1.45.0",
]
